# Generated by Django 5.1.7 on 2025-03-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('item_seq', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('entp_name', models.CharField(max_length=255)),
                ('chart', models.CharField(blank=True, max_length=255, null=True)),
                ('item_image', models.URLField(blank=True, null=True)),
                ('print_front', models.CharField(blank=True, max_length=100, null=True)),
                ('print_back', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('color_class1', models.CharField(blank=True, max_length=100, null=True)),
                ('color_class2', models.CharField(blank=True, max_length=100, null=True)),
                ('line_front', models.CharField(blank=True, max_length=50, null=True)),
                ('line_back', models.CharField(blank=True, max_length=50, null=True)),
                ('leng_long', models.CharField(blank=True, max_length=10, null=True)),
                ('leng_short', models.CharField(blank=True, max_length=10, null=True)),
                ('thick', models.CharField(blank=True, max_length=10, null=True)),
                ('img_regist_ts', models.CharField(blank=True, max_length=20, null=True)),
                ('item_permit_date', models.CharField(blank=True, max_length=20, null=True)),
                ('form_code_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mark_code_front_anal', models.CharField(blank=True, max_length=255, null=True)),
                ('mark_code_back_anal', models.CharField(blank=True, max_length=255, null=True)),
                ('mark_code_front_img', models.CharField(blank=True, max_length=255, null=True)),
                ('mark_code_back_img', models.CharField(blank=True, max_length=255, null=True)),
                ('item_eng_name', models.CharField(blank=True, max_length=255, null=True)),
                ('change_date', models.CharField(blank=True, max_length=20, null=True)),
                ('mark_code_front', models.CharField(blank=True, max_length=255, null=True)),
                ('mark_code_back', models.CharField(blank=True, max_length=255, null=True)),
                ('edi_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bizrno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
