# Generated by Django 5.1.7 on 2025-03-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0002_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginfo',
            name='ee_doc_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='ee_doc_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='nb_doc_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='nb_doc_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='ud_doc_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginfo',
            name='ud_doc_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
