# Generated by Django 5.1.7 on 2025-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0004_alter_appearance_options_alter_druginfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='entp_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='item_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='entp_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='item_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
