# Generated by Django 5.1.7 on 2025-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0005_alter_appearance_entp_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='item_seq',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='item_seq',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
