# Generated by Django 5.1.7 on 2025-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0006_alter_appearance_item_seq_alter_druginfo_item_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='item_seq',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='druginfo',
            name='item_seq',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
